config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions' }

  root 'productivities#index'

  resources :productivities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/productivity.rb
class Productivity < ApplicationRecord
  belongs_to :user

  scope :by_user, ->(user) { where user_id: user }
  scope :ordered, -> { order(day: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/productivities_controller.rb
class ProductivitiesController < ApplicationController
  before_action :set_productivity, only: [:show, :edit, :update, :destroy]

  # GET /productivities
  # GET /productivities.json
  def index
    @productivities = Productivity.by_user(current_user).ordered
  end

  # GET /productivities/1
  # GET /productivities/1.json
  def show
  end

  # GET /productivities/new
  def new
    @productivity = Productivity.new
  end

  # GET /productivities/1/edit
  def edit
  end

  # POST /productivities
  # POST /productivities.json
  def create
    @productivity = Productivity.new(productivity_params)

    @productivity.user = current_user

    respond_to do |format|
      if @productivity.save
        format.html { redirect_to @productivity, notice: 'Productivity was successfully created.' }
        format.json { render :show, status: :created, location: @productivity }
      else
        format.html { render :new }
        format.json { render json: @productivity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productivities/1
  # PATCH/PUT /productivities/1.json
  def update
    @productivity.user = current_user
    respond_to do |format|
      if @productivity.update(productivity_params)
        format.html { redirect_to @productivity, notice: 'Productivity was successfully updated.' }
        format.json { render :show, status: :ok, location: @productivity }
      else
        format.html { render :edit }
        format.json { render json: @productivity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productivities/1
  # DELETE /productivities/1.json
  def destroy
    @productivity.destroy
    respond_to do |format|
      format.html { redirect_to productivities_url, notice: 'Productivity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productivity
      @productivity = Productivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def productivity_params
      params.require(:productivity).permit(:day, :focus, :prioritie1, :prioritie2, :prioritie3, :prioritie4, :prioritie5, :to_avoid1, :to_avoid2, :to_avoid3, :learn, :grateful1, :grateful2, :grateful3, :note)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout 'devise'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productivities_helper.rb
module ProductivitiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Produtividade</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'dashboard', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Dash da produtividade</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="#">Sign out</a>
      </li>
    </ul>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="<%=productivities_path%>">
                <span data-feather="home"></span>
                Folha da produtividade <span class="sr-only">(current)</span>
              </a>
            </li>
            </li>
          </ul>
        </div>
      </nav>
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <%= yield %>
      </main>
    </div>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Produtividade</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productivities/_form.html.erb
<%= form_with(model: productivity, local: true) do |form| %>
  <% if productivity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(productivity.errors.count, "error") %> prohibited this productivity from being saved:</h2>

      <ul>
      <% productivity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day, id: :productivity_day %>
  </div>

  <div class="field">
    <%= form.label :focus %>
    <%= form.text_field :focus, id: :productivity_focus %>
  </div>

  <div class="field">
    <%= form.label :prioritie1 %>
    <%= form.text_field :prioritie1, id: :productivity_prioritie1 %>
  </div>

  <div class="field">
    <%= form.label :prioritie2 %>
    <%= form.text_field :prioritie2, id: :productivity_prioritie2 %>
  </div>

  <div class="field">
    <%= form.label :prioritie3 %>
    <%= form.text_field :prioritie3, id: :productivity_prioritie3 %>
  </div>

  <div class="field">
    <%= form.label :prioritie4 %>
    <%= form.text_field :prioritie4, id: :productivity_prioritie4 %>
  </div>

  <div class="field">
    <%= form.label :prioritie5 %>
    <%= form.text_field :prioritie5, id: :productivity_prioritie5 %>
  </div>

  <div class="field">
    <%= form.label :to_avoid1 %>
    <%= form.text_field :to_avoid1, id: :productivity_to_avoid1 %>
  </div>

  <div class="field">
    <%= form.label :to_avoid2 %>
    <%= form.text_field :to_avoid2, id: :productivity_to_avoid2 %>
  </div>

  <div class="field">
    <%= form.label :to_avoid3 %>
    <%= form.text_field :to_avoid3, id: :productivity_to_avoid3 %>
  </div>

  <div class="field">
    <%= form.label :learn %>
    <%= form.text_area :learn, id: :productivity_learn %>
  </div>

  <div class="field">
    <%= form.label :grateful1 %>
    <%= form.text_field :grateful1, id: :productivity_grateful1 %>
  </div>

  <div class="field">
    <%= form.label :grateful2 %>
    <%= form.text_field :grateful2, id: :productivity_grateful2 %>
  </div>

  <div class="field">
    <%= form.label :grateful3 %>
    <%= form.text_field :grateful3, id: :productivity_grateful3 %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.number_field :note, id: :productivity_note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productivities/edit.html.erb
<h1>Editing Productivity</h1>

<%= render 'form', productivity: @productivity %>

<%= link_to 'Show', @productivity %> |
<%= link_to 'Back', productivities_path %>

app/views/productivities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folhas de produtividade</h1>

<%= link_to 'Registrar produtividade do dia', new_productivity_path, class: 'btn btn-primary' %>

<table class="table table-hover" style="margin-top: 10px">
  <thead>
    <tr>
      <th scope="col">Data</th>
      <th scope="col">Foco do dia</th>
      <th scope="col">Prioridade 1</th>
      <th scope="col">Prioridade 2</th>
      <th scope="col">Prioridade 3</th>
      <th scope="col">Prioridade 4</th>
      <th scope="col">Prioridade 5</th>
      <th scope="col">Nota do dia</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productivities.each do |productivity| %>
      <tr>
        <td><%= productivity.day %></td>
        <td><%= productivity.focus %></td>
        <td><%= productivity.prioritie1 %></td>
        <td><%= productivity.prioritie2 %></td>
        <td><%= productivity.prioritie3 %></td>
        <td><%= productivity.prioritie4 %></td>
        <td><%= productivity.prioritie5 %></td>
        <td><%= productivity.note %></td>
        <td><%= link_to 'Show', productivity %></td>
        <td><%= link_to 'Edit', edit_productivity_path(productivity) %></td>
        <td><%= link_to 'Destroy', productivity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/productivities/new.html.erb
<h1>New Productivity</h1>

<%= render 'form', productivity: @productivity %>

<%= link_to 'Back', productivities_path %>

app/views/productivities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @productivity.day %>
</p>

<p>
  <strong>Focus:</strong>
  <%= @productivity.focus %>
</p>

<p>
  <strong>Prioritie1:</strong>
  <%= @productivity.prioritie1 %>
</p>

<p>
  <strong>Prioritie2:</strong>
  <%= @productivity.prioritie2 %>
</p>

<p>
  <strong>Prioritie3:</strong>
  <%= @productivity.prioritie3 %>
</p>

<p>
  <strong>Prioritie4:</strong>
  <%= @productivity.prioritie4 %>
</p>

<p>
  <strong>Prioritie5:</strong>
  <%= @productivity.prioritie5 %>
</p>

<p>
  <strong>To avoid1:</strong>
  <%= @productivity.to_avoid1 %>
</p>

<p>
  <strong>To avoid2:</strong>
  <%= @productivity.to_avoid2 %>
</p>

<p>
  <strong>To avoid3:</strong>
  <%= @productivity.to_avoid3 %>
</p>

<p>
  <strong>Learn:</strong>
  <%= @productivity.learn %>
</p>

<p>
  <strong>Grateful1:</strong>
  <%= @productivity.grateful1 %>
</p>

<p>
  <strong>Grateful2:</strong>
  <%= @productivity.grateful2 %>
</p>

<p>
  <strong>Grateful3:</strong>
  <%= @productivity.grateful3 %>
</p>

<p>
  <strong>Note:</strong>
  <%= @productivity.note %>
</p>

<%= link_to 'Edit', edit_productivity_path(@productivity) %> |
<%= link_to 'Back', productivities_path %>